apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: @ProjectIdGoesHere@-is-@VersionTagGoesHere@
    labels:
      app: @ProjectIdGoesHere@-@VersionTagGoesHere@
      region: primary
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: @DockerImageRepoGoesHere@/@ProjectIdGoesHere@:@VersionTagGoesHere@
      importPolicy:
        scheduled: true
      name: master
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: @ProjectIdGoesHere@
      run: @ProjectIdGoesHere@-@VersionTagGoesHere@
    name: @ProjectIdGoesHere@-dc-@VersionTagGoesHere@
  spec:
    replicas: 1
    selector:
      run: @ProjectIdGoesHere@-@VersionTagGoesHere@
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          run: @ProjectIdGoesHere@-@VersionTagGoesHere@
          partof: @ProjectIdGoesHere@-@VersionTagGoesHere@
      spec:
        containers:
        - image: @DockerImageRepoGoesHere@/@ProjectIdGoesHere@:@VersionTagGoesHere@
          imagePullPolicy: Always
          name: @ProjectIdGoesHere@-pod-@VersionTagGoesHere@
          resources: {}
          terminationMessagePath: /dev/termination-log
          ports:
            -
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              cpu: 1500m
              memory: 512Mi
            requests:
              cpu: 400m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 4
            successThreshold: 1
            failureThreshold: 15
          readinessProbe:
            httpGet:
              path: /lc/ping
              port: 8081
            initialDelaySeconds: 12
            timeoutSeconds: 8
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 15
          lifecycle:
            preStop:
              httpGet:
                  path: "/lc/stop"
                  port: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: @ProjectIdGoesHere@-svc-@VersionTagGoesHere@
    labels:
      app: @ProjectIdGoesHere@
  spec:
    ports:
      - port: 8081
        targetPort: 8081
    selector:
       run: @ProjectIdGoesHere@-@VersionTagGoesHere@
kind: List
metadata: {}

